// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbrgpzdxttzlvvryysaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNicmdwemR4dHR6bHZ2cnl5c2FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQ3NjE4NjQsImV4cCI6MjA0MDMzNzg2NH0.6Ugcs-bIFa3vWC8pcN8iLFJ9kIRNeaZdEWGlrNySaHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);